//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFotonDesktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int ID_venta { get; set; }
        public Nullable<System.TimeSpan> Fecha { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public decimal Precio { get; set; }
        public Nullable<int> ID_cliente { get; set; }
        public Nullable<int> ID_producto { get; set; }
        public Nullable<int> ID_vendedor { get; set; }
        public Nullable<bool> DiscontinueDate { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Vendedor Vendedor { get; set; }
    }
}
